DROP TABLE IF EXISTS HOUSING_ADS ;
DROP TABLE IF EXISTS ITEM_ADS ;
DROP TABLE IF EXISTS JOB_POSTING ;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS RENTAL_ADS ;
DROP TABLE IF EXISTS USER_OPINION ;
DROP TABLE IF EXISTS USER ;
DROP TABLE IF EXISTS ADRESS;
